### ISSUE TITLE
Distributed set-up is broken

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#3692]
Running a distributed Opencast of `develop`

- 4a48816 (current HEAD) is broken
- 5cf4826 is broken
- 315707c is good

The initial error seems to be:
```
2022-04-21T18:21:55,866 | ERROR | (Main$1:328) - Bundle opencast-cover-image-remote [80] EventDispatcher: Error during dispatch. (java.lang.NoClassDefFoundError: org/opencastproject/security/api/TrustedHttpClient)
java.lang.NoClassDefFoundError: org/opencastproject/security/api/TrustedHttpClient
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods([Class.java:3166](http://class.java:3166/)) ~[?:?]
        at java.lang.Class.getDeclaredMethods([Class.java:2309](http://class.java:2309/)) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObjectAssignableMethod([BindMethod.java:477](http://bindmethod.java:477/)) ~[?:?]
        …
```

Looking at the commits between good and bad commits on the failing `cover-image-remote` the prime candidate for the cause seems to be #3385:

```
❯ git log --oneline 315707c..5cf4826626a389aa037145fe218cc551d31ccd3f -- modules/cover-image-remote
fbf50f6482 (upstream/pr/3385) clean up osgi xml files
994b1234df remove explicit definition of static policy
660ddea364 override missing methods from super class
54a31f308f migrate osgi xml to dc via script with 🐛s, ide and manual cleanup
```

A more detailed log can be found at:
https://data.lkiesow.io/opencast/opencast-distributed-develop-broken.log
